### ISSUE TITLE
Confusion on UI for create/update device

### ISSUE THREAD

**Issue by pspada** [raptorbox/raptor-ui#5]
A few small UI issues I found.

1.  _Description_ appears twice (the one before `UserId` text field should be changed)
2. `UserId` value seems to be assigned automatically ignoring what is set at creation time. In such a case probably it should not be asked when creating the device?
3. _"Enter Stream Name"_ does not look as an editable field so it creates a bit of confusion
4. Whatever I input in `Channe Unit` field is ignored

**Comment by ansriaz** [comment]
1. _Description_ changed to _"Change User"_ on edit page.
2. removed from create page and assigning the user id value automatically. On edit page, one change change the user.
3. A bottom border is added to this editable field. 
4. _Change Unit_ field is removed as it is not been used in system.
